// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEAsXvvJHanhjHsw8JRIiwtNZy8bm88Hc',
    appId: '1:1058137172905:web:e0a36e9cb40cd488a472b8',
    messagingSenderId: '1058137172905',
    projectId: 'componentes-aa62a',
    authDomain: 'componentes-aa62a.firebaseapp.com',
    storageBucket: 'componentes-aa62a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkKf6AniqRlOViIrbGrVpr5FRCPt2vRmA',
    appId: '1:1058137172905:android:5ee01729f94d0c99a472b8',
    messagingSenderId: '1058137172905',
    projectId: 'componentes-aa62a',
    storageBucket: 'componentes-aa62a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHS32l9FYHO1Ls59OrbSFU6N5TU36xa80',
    appId: '1:1058137172905:ios:07546a5b83a16d27a472b8',
    messagingSenderId: '1058137172905',
    projectId: 'componentes-aa62a',
    storageBucket: 'componentes-aa62a.appspot.com',
    iosBundleId: 'com.example.practica3',
  );
}
